# Generated by Django 5.1.5 on 2025-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_course_classdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='remainingCapacity',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
