# Generated by Django 5.1.5 on 2025-02-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_course_remainingcapacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationalID',
            field=models.CharField(max_length=10),
        ),
    ]
